name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selection of the target endpoint'
        type: environment
        default: 'production'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      packages: read
      id-token: write
    steps: 
    - name: Az CLI login
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Configure Azure CLI
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        
    - name: Create container app
      run: |
        fqdn=$(az containerapp create -n oidc-auth-app-prod -g oidc-auth-app \
            --image ghcr.io/helaili/github-oidc-auth-app:main --environment managedEnvironment-oidcauthapp-8f08 \
            --ingress external --target-port 9090 \
            --registry-server gcr.io --registry-username helaili --registry-password dummy \
            --secrets key=${{ secrets.PRIVATE_KEY }} \
            --env-vars PORT=9090 PRIVATE_KEY=secretref:key APP_ID=${{ secrets.APP_ID }} \
            --query properties.configuration.ingress.fqdn -o tsv)