name: TEST VAR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selection of the target endpoint'
        type: environment
        default: 'production'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment }}
    permissions:
      packages: read
      id-token: write
      actions: write
    steps: 
    - name: Update env with curl
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
        script: |
          github.request("GET /repositories/${{ github.repository_id }}/environments/${{ github.event.inputs.environment }}/variables/ENDPOINT").then((result) => {
            console.log('ENDPOINT', result)
          }).catch((err) => {
            console.log('ENDPOINT', err)
          })

          github.request("GET /repositories/${{ github.repository_id }}/environments/${{ github.event.inputs.environment }}/variables/XXX").then((result) => {
            console.log('XXX', result)
          }).catch((err) => {
            console.log('XXX', err)
          })
  
