name: Manual Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selection of the target endpoint'
        type: environment
        default: 'production'
        required: true

jobs:
  run:
    uses: ./.github/workflows/deployment-test.yml
    permissions:
      id-token: write
    with:
      endpoint: ${{ vars.ENDPOINT }}
      installationId: ${{ vars.INSTALLATION_ID }}