name: Manual Deployment Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selection of the target environment'
        type: environment
        default: 'production'
        required: true

jobs:
  setenv:
    name: Set environment variables
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs: 
      endpoint: ${{ steps.setenv.outputs.endpoint }}
      login: ${{ steps.setenv.outputs.login }}
    steps:
      - name: Set environment variables
        id: setenv
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Endpoint: ${{ vars.ENDPOINT }}"
          echo "Login: ${{ vars.LOGIN }}" 
          echo "endpoint=${{ vars.ENDPOINT }}" >> $GITHUB_OUTPUT
          echo "login=${{ vars.LOGIN }}" >> $GITHUB_OUTPUT
          
  test:
    uses: ./.github/workflows/deployment-test.yml
    needs: setenv
    permissions:
      id-token: write
    with:
      endpoint: ${{ needs.setenv.outputs.endpoint }}
      login: ${{ needs.setenv.outputs.login }}
      environment: ${{ inputs.environment }}
