name: Manual Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selection of the target endpoint'
        type: environment
        default: 'production'
        required: true


jobs:
  setenv:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Set environment variables
        run: |
          echo "::set-output name=endpoint::${{ vars.ENDPOINT }}"
          echo "::set-output name=installationId::${{ vars.INSTALLATION_ID }}"

  run:
    uses: ./.github/workflows/deployment-test.yml
    needs: setenv
    permissions:
      id-token: write
    with:
      endpoint: ${{ needs.setenv.outputs.endpoint }}
      installationId: ${{ needs.setenv.outputs.installationId }}
