name: Manual Deployment Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selection of the target endpoint'
        type: environment
        default: 'production'
        required: true

jobs:
  setenv:
    name: Set environment variables
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs: 
      endpoint: ${{ steps.setenv.outputs.endpoint }}
      installationId: ${{ steps.setenv.outputs.installationId }}
    steps:
      - name: Set environment variables
        id: setenv
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Endpoint: ${{ vars.ENDPOINT }}"
          echo "Installation ID: ${{ vars.INSTALLATION_ID }}" 
          echo "endpoint=${{ vars.ENDPOINT }}" >> $GITHUB_OUTPUT
          echo "installationId=${{ vars.INSTALLATION_ID }}" >> $GITHUB_OUTPUT
          
  run:
    uses: ./.github/workflows/deployment-test.yml
    needs: setenv
    permissions:
      id-token: write
    with:
      endpoint: ${{ needs.setenv.outputs.endpoint }}
      installationId: ${{ needs.setenv.outputs.installationId }}
