name: Manual Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selection of the target endpoint'
        type: environment
        default: 'production'
        required: true


jobs:
  setenv:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Set environment variables
        run: |
          echo "name=endpoint::${{ vars.ENDPOINT }}" >> $GITHUB_OUTPUT
          echo "name=installationId::${{ vars.INSTALLATION_ID }}" >> $GITHUB_OUTPUT
  
  debug:
    runs-on: ubuntu-latest
    needs: setenv
    steps:
      - name: Echo environment variables
        run: |
          echo "Endpoint: ${{ needs.setenv.outputs.endpoint }}"
          echo "Installaion ID: ${{ needs.setenv.outputs.installationId }}"

  run:
    uses: ./.github/workflows/deployment-test.yml
    needs: setenv
    permissions:
      id-token: write
    with:
      endpoint: ${{ needs.setenv.outputs.endpoint }}
      installationId: ${{ needs.setenv.outputs.installationId }}
