name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selection of the target endpoint'
        type: environment
        default: 'sandbox'
        required: true

jobs:
  
  setenv:
    name: Set environment variables
    runs-on: ubuntu-latest
    environment: production
    outputs: 
      installationId: ${{ steps.setenv.outputs.installationId }}
      environment: ${{ steps.setenv.outputs.environment }}
    steps:
      - name: Set environment variables
        id: setenv
        run: |
          echo "Installation ID: ${{ vars.INSTALLATION_ID }}" 
          echo "installationId=${{ vars.INSTALLATION_ID }}" >> $GITHUB_OUTPUT
  
  deploy:
    name: Deploy
    needs:
      - setenv
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.environment }}
      cancel-in-progress: true
    uses: ./.github/workflows/deploy-azure-container-app.yml
    secrets: inherit 
    permissions:
      id-token: write
      packages: read
      actions: write
    with:
      environment: ${{ inputs.environment }}
  
  test:
    uses: ./.github/workflows/deployment-test.yml
    needs:
      - setenv
      - deploy
    permissions:
      id-token: write
    with:
      endpoint: ${{ vars.endpoint }}
      installationId: ${{ needs.setenv.outputs.installationId }}
